<?php

declare(strict_types=1);

namespace App\Services;

use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Http;
use RuntimeException;

/**
 * Writes wp-config.php without WP-CLI so WordPress is never bootstrapped during clone
 * (avoids "The site you have requested is not installed" from wp config create).
 */
final class WpConfigGenerator
{
    private const SALT_URL = 'https://api.wordpress.org/secret-key/1.1/salt/';

    public function writeForClone(string $siteRoot, string $tablePrefix): void
    {
        if (! preg_match('/^[a-zA-Z0-9_]+$/', $tablePrefix)) {
            throw new \InvalidArgumentException('Invalid database table prefix.');
        }

        $wpDir = $siteRoot.DIRECTORY_SEPARATOR.'wp';
        if (! is_dir($wpDir)) {
            throw new RuntimeException("Missing WordPress directory: {$wpDir}");
        }

        $response = Http::timeout(20)->get(self::SALT_URL);
        if (! $response->successful()) {
            throw new RuntimeException('Could not download WordPress salt keys from api.wordpress.org.');
        }

        $salts = trim($response->body());
        if ($salts === '' || stripos($salts, '<html') !== false || stripos($salts, 'not installed') !== false) {
            throw new RuntimeException('Salt endpoint returned HTML or unexpected content (check network / proxy).');
        }
        $defineCount = preg_match_all('/^define\s*\(/m', $salts);
        if ($defineCount === false || $defineCount < 8) {
            throw new RuntimeException('WordPress salt API returned fewer than 8 define() lines.');
        }

        $dbName = (string) config('lando_dev.defaults.db_name');
        $dbUser = (string) config('lando_dev.defaults.db_user');
        $dbPass = (string) config('lando_dev.defaults.db_password');
        $dbHost = (string) config('lando_dev.defaults.db_host');

        $e = static fn (string $s): string => var_export($s, true);

        $php = <<<PHP
<?php
/**
 * Generated by Lando Studio clone (PHP generator — not wp config create).
 */

define( 'DB_NAME', {$e($dbName)} );
define( 'DB_USER', {$e($dbUser)} );
define( 'DB_PASSWORD', {$e($dbPass)} );
define( 'DB_HOST', {$e($dbHost)} );
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', '' );

{$salts}

\$table_prefix = {$e($tablePrefix)};

define( 'WP_DEBUG', false );

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';

PHP;

        $target = $wpDir.DIRECTORY_SEPARATOR.'wp-config.php';
        File::put($target, $php);
    }
}
